version: '3.9'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    networks:
      - backend

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: always
    environment:
      - SONAR_JDBC_URL=jdbc:sqlserver://sqlserver:1433;databaseName=sonarqube;encrypt=false;TrustServerCertificate=true;
      - SONAR_JDBC_USERNAME=sa
      - SONAR_JDBC_PASSWORD=StrongPassword123!
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
    - "9000:9000"
    networks:
    - backend
    depends_on:
    - sqlserver

networks:
  backend:
    driver: bridge
